import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import fs from "fs";
import { run, ethers } from "hardhat";
import path from "path";
import { useEffect, useState } from 'react';




const handleClick = ((e : Event) => {
  e.preventDefault();

  const nameInput = document.querySelector('#name');
  const emailInput = document.querySelector('#email');
  const messageInput = document.querySelector('#message');

  const data ={
    name : nameInput.value,
    email : emailInput.value,
    message : messageInput.value
  }
  
  console.log(nameInput.value)
  console.log(emailInput.value)
  console.log(messageInput.value)
  fetch("/api/contractTokenMaker",{
    method: 'POST',
    headers:{
      'Content-Type' : 'application/json',
    },
      body: JSON.stringify(data),
    })

  })

function compileContractsClick() {
  fetch("/api/deploy")
    .then((response) => response.json())
    .then((data) => {
      // handle the data here
    })
    .catch((error) => {
      // handle errors here
    });
}

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {/* <button id="coolbutton" onClick={handleClick}>
            Click this button to make a .sol file
          </button> */}
          <button id="launch" onClick={compileContractsClick}>
            Click this button to compile and launch a .sol file
          </button>
          <label>Name:</label>
          <input name="name"  id="name" />
          <br></br>
          <br></br>
          <label>Email:</label>
           <input name="email" id="email"/>
          <br></br>
          <br></br>
          <label>Message:</label>
          <input name="message" id="message" />
          <br></br>
          <br></br>
          <button onClick={handleClick}>
            Submit
          </button>
          {/* <input type="submit" value="handleSubmit" /> */}
        </div>
      </main>
    </>
  );
}


